### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by mabakach**
A quick fix for two simple compilation errors.

### CODE REVIEW

**Comment by melloware** [comment]
Nice catch!  I am going to be updating this for PF14 soon

**Comment by melloware** [comment]
It's weird my automated builds were not catching this?

**Comment by mabakach** [comment]
TechnicalInfo is not referenced by any other class. In such cases javac does not complain if a package declaration does not match the folder structre, but the internal compiler of Eclipse does.
Fot the missing logger in VirtualMachine I don't have any idea, why it was not noticed.

**Comment by melloware** [comment]
Crazy!  I am going to dig a little deeper just out of curiosity.  Once again thanks for fixing it!

**Comment by melloware** [comment]
OK I just saw what you did and reverted some of it to use `@JbossLog` the correct lombok logger.

See: https://github.com/melloware/quarkus-faces/commit/de3b131c8289fc5b5ae59ca635306ddb7bb189d3

**Pull request merged**
